version: '3.1'
services:
  db:
    container_name: db
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ryan_admin
      MYSQL_PASSWORD: ryan_password
      MYSQL_DATABASE: atelier_db
    ports:
      - "3307:3306"
    volumes:
      - atelier_db:/var/lib/mysql
  app:
    build: ./
    ports:
      - "8080:8080"

volumes:
    atelier_db: {}
